import json
from pydantic import BaseModel, Field, ValidationError
from typing import Optional, Dict, Any

class SummaryFormat(BaseModel):
    """
    Defines the expected structure and content for a professionally formatted LLM response.
    This model ensures consistency and data integrity for summaries or structured
    information generated by a Language Model.
    """
    
    title: str = Field(
        ...,
        description="The main, concise title of the document or summarized content."
    )
    introduction: str = Field(
        ...,
        description="An introductory section that sets the context, provides necessary background, "
                    "and briefly outlines the scope of the document. It should smoothly lead into the body."
    )
    Description: str = Field(
        ...,
        description="The main content or detailed explanation of the subject matter. "
                    "This section should contain all primary information, arguments, or descriptions. "
                    "It can be of variable length depending on the complexity of the content."
    )
    conclusion: str = Field(
        ...,
        description="A concluding section that summarizes key points, reiterates the main message, "
                    "offers final thoughts, or suggests implications/next steps. It should provide a sense of closure."
    )